<a href="https://colab.research.google.com/github/Nitin286roxs/Python-Revision/blob/main/2.Numpy%20Module/2_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Basics of NumPy Arrays**

NumPy stands for Numerical Python. It is a Python library used for working with an array. In Python, we use the list for the array but it’s slow to process. NumPy array is a powerful N-dimensional array object and is used in linear algebra, Fourier transform, and random number capabilities. It provides an array object much faster than traditional Python lists.

Types of Array:
* One Dimensional Array
* Multi-Dimensional Array




In [1]:
# prompt:

import numpy as np

# One Dimensional Array
one_dimensional_array = np.array([1, 2, 3, 4, 5])
print("One Dimensional Array:")
print(one_dimensional_array)

# Multi-Dimensional Array
multi_dimensional_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Multi-Dimensional Array:")
print(multi_dimensional_array)


One Dimensional Array:
[1 2 3 4 5]
Multi-Dimensional Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Numpy array from iterable  

In [3]:
iterable = (a*a for a in range(5))
arr = np.fromiter(iterable, dtype=float)
print(arr)

[ 0.  1.  4.  9. 16.]


In [5]:
string = "Google Colab"
arr = np.fromiter(string, "U2")
print(arr)

['G' 'o' 'o' 'g' 'l' 'e' ' ' 'C' 'o' 'l' 'a' 'b']


# Numpy Arrange and linspace function

In [7]:
# prompt:

# Numpy Arrange and linspace function

# Arrange function
print("Arrange function:")
arr = np.arange(0, 10, 2)
print(arr)

# Linspace function
print("Linspace function:")
arr = np.linspace(3.5, 10, 3)
print(arr)


arr = np.linspace(3.5, 10, 3, dtype=np.int32)
print(arr)


Arrange function:
[0 2 4 6 8]
Linspace function:
[ 3.5   6.75 10.  ]
[ 3  6 10]


# Numpy empty, ones and zeros function

In [8]:
# prompt:

# Numpy empty, ones and zeros function

# Empty function
print("Empty function:")
arr = np.empty([3, 3])
print(arr)

# Ones function
print("Ones function:")
arr = np.ones([3, 3], dtype=np.int32)
print(arr)

# Zeros function
print("Zeros function:")
arr = np.zeros([3, 3], dtype=np.int32)
print(arr)


Empty function:
[[4.74310429e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
Ones function:
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Zeros function:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


# Numpy Sort with axis function

In [12]:
# prompt:

# Numpy Sort with axis function
print("Sort with axis function:")
arr = np.array([[3, 1, 2], [4, 5, 6], [9, 8, 7]])
print("Original array:")
print(arr)
print("Sort along axis 0:")
print(np.sort(arr, axis=0))
print("Sort along axis 1:")
print(np.sort(arr, axis=1))
print("Sort along axis -1:")
print(np.sort(arr, axis=-1))

print("Sort along axis=None:")
print(np.sort(arr, axis=None))

Sort with axis function:
Original array:
[[3 1 2]
 [4 5 6]
 [9 8 7]]
Sort along axis 0:
[[3 1 2]
 [4 5 6]
 [9 8 7]]
Sort along axis 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sort along axis -1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sort along axis=None:
[1 2 3 4 5 6 7 8 9]


# Numpy matrix multiplication

In [15]:
# prompt:

import numpy as np

# Create two matrices
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_b = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication
result = np.matmul(matrix_a, matrix_b)

# Print the result
print("Matrix multiplication result:")
print(result)



Matrix multiplication result:
[[ 58  64]
 [139 154]]


# Newaxis function in numpy

In [27]:
arr = np.arange(3,6)
print(arr)
temp = arr[:, np.newaxis]
print(temp, temp.shape)
temp = arr[:, np.newaxis, np.newaxis]
print(temp, temp.shape)

# multiplication
arr[:, np.newaxis]*arr

[3 4 5]
[[3]
 [4]
 [5]] (3, 1)
[[[3]]

 [[4]]

 [[5]]] (3, 1, 1)


array([[ 9, 12, 15],
       [12, 16, 20],
       [15, 20, 25]])